[phases.build]
dependsOn = ["install"]
cmds = [
    "...",
    "npm install",
    "npm run build"
]

[phases.start]
cmds = [
    "php artisan migrate --force --seed",
    "php artisan optimize",
    "..."
]
