[phases.build]
dependsOn = ["install"]
cmds = [
    "...",
    "npm install",
    "npm run build"
]

[phases.start]
cmds = [
    "php artisan migrate --force",
    "php artisan db:seed --force",
    "php artisan storage:link || true",
    "php artisan optimize",
    "..."
]
